version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: jejevkin/yamdb_final:latest
    restart: always
    volumes:
      - static_volume:/code/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.6-alpine
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - static_volume:/code/static/
    restart: always

